services:
  frontend:
    build: ./web-module/frontend
    ports:
      - 8000:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./web-module/fo:/app

  backend:
    build: ./web-module/backend
    ports:
      - 8080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./web-module/bo:/app

  mysql:
    image: mysql:9.0.1
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret
    volumes:
      - ./web-module/mysql:/var/lib/mysql