services:
  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:rw
      # Mount source-code for development
      - ./:/app:rw
    depends_on:
      - mysql

  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:rw
      # Mount source-code for development
      - ./:/app:rw
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  # pgsql:
  #   image: postgres:9.5
  #   environment:
  #     - POSTGRES_DB=yii2advanced
  #     - POSTGRES_USER=yii2advanced
  #     - POSTGRES_PASSWORD=secret
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgsql:/var/lib/postgresql/data

volumes:
  mysql:
